# default cluster VM configuration
master = {
    :ip => "192.168.254.1",
    :name => "master.kubernetes.local"
}
nodes = [
    {
        :ip => "192.168.254.2",
        :name => "node-1.kubernetes.local"
    }
]

Vagrant.configure("2") do |config|  
    config.vm.box = "debian/buster64"
    # shared folder for data sharing between master and nodes
    config.vm.synced_folder "./", "/shared"
    # install the nodes dependencies (docker, kubectl, kubeadm, etc)
    config.vm.provision "shell", 
        path: "../../kubernetes/install/node/bootstrap/debian"
    # default vm configuratons
    config.vm.provider "virtualbox" do |vm|
        vm.memory =  2048
        vm.cpus = 2
    end
    # create the kubernetes master node
    config.vm.define master[:name] do |config|
        config.vm.hostname = master[:name]  
        # assign a private ip to the master
        config.vm.network :private_network, 
            ip: master[:ip], 
            auto_config: false
        # initialize control plane
        config.vm.provision "shell", 
            path: "../../kubernetes/install/master/bootstrap",
            env: {"CONTROL_PLANE_ENDPOINT" => master[:name]}              
        # copy the kube.config to the shared directory so it can be used to admin the cluster
        config.vm.provision "shell", inline:"
            cp /etc/kubernetes/admin.conf /shared/kube.config"
        # write the join command into the shared folder
        config.vm.provision "shell", 
            inline:" kubeadm token create --print-join-command > /shared/join.cmd"
        # expose kubernetes api server 
        config.vm.network "forwarded_port", 
            guest: 6443, 
            host: 6443
    end
    # setup kubernetes worker node
    nodes.each do |node|
        config.vm.define node[:name] do |config|
            # set the vm hostnamez
            config.vm.hostname = node[:name]
            # assign a private ip to the master
            config.vm.network :private_network, 
                ip: node[:ip], 
                auto_config: false
            # write the master hotname into the hosts file
            config.vm.provision "shell", 
                inline:"echo '%s \t %s' >> /etc/hosts" % [master[:ip],master[:name]]
            # join the worker node on the cluster
            config.vm.define node[:name] do |config|
                config.vm.provision "shell", 
                    inline:"source /shared/join.cmd"                
            end           
        end           
    end
end
