
# default virtual machines configurations
$LINUX_DIST="debian/buster64"
$VM_MEMORY_MB=2048
$VM_CPU_CORES=2

$MASTER_FQDN="master.kubernetes.cluster"
$MASTER_IP_ADDR="10.0.0.1"

Vagrant.configure("2") do |config|  
    config.vm.box = $LINUX_DIST

    # shared folder for data sharing between master and nodes
    config.vm.synced_folder "./", "/shared"

    # virtual machines computing resources
    config.vm.provider "virtualbox" do |vbox|
        vbox.memory = $VM_MEMORY_MB
        vbox.cpus = $VM_CPU_CORES
    end

    # kubernetes node master
    config.vm.define :master do |master|
        master.vm.hostname = $MASTER_FQDN
        master.vm.network :private_network, ip: $MASTER_IP_ADDR

        # initialize node master
        master.vm.provision "shell", 
            path: "../../kubernetes/install/master/bootstrap",
            env: {"CONTROL_PLANE_ENDPOINT" => master.vm.hostname}

        # write the join command into the shared folder
        master.vm.provision "shell", inline:"
            kubeadm token create --print-join-command > /shared/join"
    end

    # kubernetes worker node 1
    config.vm.define :node1 do |node1|
        node1.vm.hostname = "node1.cluster.local"
        node1.vm.network :private_network, ip: "10.0.0.2"
        # run the join command from the shared folder
        node1.vm.provision "shell", inline:"source /shared/join"
        node1.vm.provision "shell", inline:"echo %s %s >> /etc/hosts" % [$MASTER_FQDN,$MASTER_IP_ADDR]
    end
    
    # install the nodes dependencies (docker, kubectl, kubeadm, etc)
    config.vm.provision "shell", path: "../../kubernetes/install/node/bootstrap/debian"
end
