#!/bin/bash

curl -s https://fluxcd.io/install.sh | sudo bash

export GITHUB_TOKEN=<your-token>

flux bootstrap github \
  --owner=jsoliveir \
  --repository=k8s-workload-definitions \
  --path=clusters/development \

flux bootstrap github \
  --owner=jsoliveir \
  --repository=k8s-workload-definitions \
  --path=clusters/production \