#!/bin/bash
# run as root

CONTROL_PLANE_ENDPOINT=${CONTROL_PLANE_ENDPOINT:-"localhost"}
POD_NET_CIDR=${POD_NET_CIDR:-"10.0.0.1/24"}

kubeadm init \
    --control-plane-endpoint=$CONTROL_PLANE_ENDPOINT \
    --pod-network-cidr=$POD_NET_CIDR \
    --ignore-preflight-errors=NumCPU \
    --ignore-preflight-errors=Mem 

kubeadm token create --print-join-command